# Generated by Django 4.1.2 on 2022-11-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_player",
            field=models.BooleanField(null=True),
        ),
    ]
