# Generated by Django 4.1.3 on 2022-11-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
