# Generated by Django 4.1.2 on 2022-11-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_is_player"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_ad",
        ),
        migrations.AlterField(
            model_name="user",
            name="total_score",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
